SELECT SQ.AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM (SELECT AUTHOR_ID, CATEGORY, SUM(PRICE*SALES) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES BS
ON (B.BOOK_ID = BS.BOOK_ID)
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY AUTHOR_ID, CATEGORY) AS SQ JOIN AUTHOR A
ON (SQ.AUTHOR_ID = A.AUTHOR_ID)
ORDER BY SQ.AUTHOR_ID ASC, CATEGORY DESC;