SELECT CR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CR JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRH
ON (CR.CAR_ID = CRH.CAR_ID)
WHERE CAR_TYPE = "세단" AND MONTH(START_DATE) = 10
GROUP BY CR.CAR_ID
ORDER BY CR.CAR_ID DESC;