SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO FI JOIN FISH_NAME_INFO FNI
ON (FI.FISH_TYPE = FNI.FISH_TYPE)
WHERE (LENGTH, FI.FISH_TYPE)
IN (SELECT MAX(LENGTH), FISH_TYPE FROM FISH_INFO GROUP BY FISH_TYPE)
ORDER BY ID ASC;