SELECT CONCAT("/home/grep/src/", UGF.BOARD_ID, "/", FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD USB JOIN USED_GOODS_FILE UGF
ON (USB.BOARD_ID = UGF.BOARD_ID)
WHERE VIEWS IN (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;